### ISSUE TITLE
Unhandled Exception: Bad state: Cannot emit new states after calling close

### ISSUE THREAD

**Issue by abdullah230695** [NaagAlgates/flutter_no_internet_widget#1]
Not works in root of the widget

**class MyApp extends StatelessWidget {
  // const MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      home: InternetWidget(
        online: InitializerWidget(),
        offline:Scaffold(
          body: Center(child: Text('No Internet')),
        ),
        whenOnline: () => InitializerWidget(),
        whenOffline: () => Scaffold(
          body: Center(child: Text('No Internet')),
        ),
      ),
    
    );
  }
}**

**Comment by NaagAlgates** [comment]
Thanks, @abdullah230695 . Can you please add a screenshot of the error you received or a sample video?

**Comment by abdullah230695** [comment]
Hi, actually the problem is ...
Consider that you have 3 screens and one main class , if you set InternetWidget in only main class and you moved to 1st screen then if you do data on/off that error occurs,  InternetWidget will works in all screens for each screen we need to implement that... But this needs to be implement on only main widget...

Pls set for globally detect it for all classes

**Comment by NaagAlgates** [comment]
Thank you @abdullah230695 , I can reproduce this issue and I've picked it for development. I will try to fix this as soon as I can.

**Comment by abdullah230695** [comment]
And another issue here , if wifi is on and no internet connection is there then it won't detect the internet connection, it only checks that device is connected to wifi or internet

**Comment by NaagAlgates** [comment]
Create a separate ticket for this please, @abdullah230695

**Comment by abdullah230695** [comment]
Ok bro , thank you

**Comment by NaagAlgates** [comment]
The fix is available in the version: `0.0.6`

**Comment by abdullah230695** [comment]
ok , thanks for the update
