### ISSUE TITLE
debugShowCheckedModeBanner is showing always false

### ISSUE THREAD

**Issue by MabudAlam** [NaagAlgates/flutter_no_internet_widget#5]
Hey, 
I was trying your package, everything is working fine. Except the debugShowCheckedModeBanner is always showing true even after adding  " debugShowCheckedModeBanner: false,".

Flutter version: 3.3.4

My main.dart
https://pastebin.com/fH20WnFr
![Screenshot_1665337415](https://user-images.githubusercontent.com/47685150/194771518-90561526-db09-44c9-9ae7-8d9591084ef8.png)

**Comment by MabudAlam** [comment]
I have fixed the problem by adding "debugShowCheckedModeBanner: false," inside InternetWidget's material widget.

**Comment by NaagAlgates** [comment]
Thank you @Pavel401 . This is now fixed in the new version 0.0.7
